#blue
version: '3'
services:
  # 서비스의 이름
  backend:
    # 현재 디렉토리에서의 Dockerfile을 사용하여 Docker 이미지를 빌드
    build: .
    # 호스트의 8081 포트와 컨테이너의 80 포트를 매핑
    ports:
      - "8081:8080"
    # 컨테이너의 이름
    container_name: spring-blue
    environment:
      - spring.profiles.active=dev-blue
    # 컨테이너가 속한 네트워크
    networks:
      - our_net
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5673"
      - "15673:15673"
    container_name: rabbitmq-blue
    networks:
      - our_net
networks:
  our_net:
    driver: bridge