logging:
  level:
    root: info

spring:
  rabbitmq:
    host: rabbitmq-green
    port: 5674
    username: guest
    password: guest

rabbitmq:
  queue.name: sample.queue
  exchange.name: sample.exchange
  routing.key: sample.key